### ISSUE TITLE
Remove index.html

### ISSUE THREAD

**Issue by tobyhodges** [ericcrandall/2022-06-08-SEAS-Islands-Alliance#1]
@ericcrandall your workshop webpage is currently being served as the `index.html` file in this repository, instead of an HTML page built and served from the `index.md` source file.

If you remove the `index.html` file, and update the remaining fields in the YAML header of `index.md`, in this repository, you should see the correct page served at https://ericcrandall.github.io/2022-06-08-SEAS-Islands-Alliance/

Please let me know if you need any further assistance.

**Comment by ericcrandall** [comment]
Ah! Got it. Thanks
